FROM centos:centos7

RUN yum -y update
RUN yum -y install wget tar gcc make
RUN wget http://prdownloads.sourceforge.net/aa-project/aalib-1.4rc4.tar.gz
RUN tar xvf aalib-1.4rc4.tar.gz
WORKDIR /aalib-1.4.0
RUN ./configure
RUN make install

WORKDIR /
RUN wget http://prdownloads.sourceforge.net/aa-project/aview-1.3.0rc1.tar.gz
RUN tar xvf aview-1.3.0rc1.tar.gz
WORKDIR /aview-1.3.0
RUN ./configure
RUN make install

CMD ["/usr/bin/tail", "-f", "/var/log/messages"]

